<Project Sdk="MSTest.Sdk">
  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" />
    <ProjectReference Include="..\Enochian.Cdsl\Enochian.Cdsl.csproj" />
    <ProjectReference Include="..\Enochian\Enochian.csproj" />
    <ProjectReference Include="..\Enochian.Provenance\Enochian.Provenance.csproj" />
  </ItemGroup>
</Project>
